name: test-and-publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: s3
          DEFAULT_REGION: us-east-1
          FORCE_NONINTERACTIVE: 'true'
          HOSTNAME: localhost
          USE_SSL: false
          DEBUG: 1
        ports:
          - 4566:4566
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: chrislennon/action-aws-cli@v1.1
    - name: Increase NPM version
      run: |
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        npm version patch
    - name: Set up as module
      run: |
        aws --endpoint-url http://localstack:4572 s3 mb s3://testing
        HERE=`pwd`
        mkdir /tmp/project
        cd /tmp/project
        npm init -y
        npm install faker puppeteer@2.1.1 @userdashboard/dashboard @userdashboard/storage-s3
        npm install -g mocha
        rm node_modules/@userdashboard/storage-s3/*.js
        rm -rf node_modules/@userdashboard/storage-s3/src
        cp $HERE/*.js node_modules/@userdashboard/storage-s3
        cp -R $HERE/src/ node_modules/@userdashboard/storage-s3/src/
        echo "global.applicationPath = __dirname" > main.js
      env:
        SECRET_ACCESS_KEY: "using-mock-aws-s3"
        ACCESS_KEY_ID: "using-mock-aws-s3"
    - name: Test unencrypted S3-compatible storage
      run: |
        cd /tmp/project 
        mocha --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
        cd $HERE
      env:
        NODE_ENV: "testing"
        FAST_START: "true"
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-s3"
        S3_ENDPOINT: "http://localhost:4566"
        S3_BUCKET_NAME: "testing"
        SECRET_ACCESS_KEY: "using-mock-aws-s3"
        ACCESS_KEY_ID: "using-mock-aws-s3"
        GENERATE_SITEMAP_TXT: "false"
        GENERATE_API_TXT: "false"
        LOG_LEVEL: "info,warn,error,log"
    - name: Test encrypted S3-compatible storage
      run: |
        cd /tmp/project 
        mocha --file main.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js"
        cd $HERE
      env:
        NODE_ENV: testing
        FAST_START: "true"
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-s3"
        S3_ENDPOINT: "http://localhost:4566"
        S3_BUCKET_NAME: "testing"
        SECRET_ACCESS_KEY: "using-mock-aws-s3"
        ACCESS_KEY_ID: "using-mock-aws-s3"
        GENERATE_SITEMAP_TXT: "false"
        GENERATE_API_TXT: "false"
        ENCRYPTION_SECRET: "12345678901234567890123456789012"
        ENCRYPTION_SECRET_IV: "1234123412341234"
        LOG_LEVEL: "info,warn,error,log"
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}