name: test-and-publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    services:
      localstack:
        image: localstack/localstack:latest
        env:
          SERVICES: s3
          DEFAULT_REGION: us-east-1
          FORCE_NONINTERACTIVE: 'true'
          HOSTNAME: localhost
          USE_SSL: false
          DEBUG: 1
        ports:
          - "4566-4599:4566-4599"
    steps:
    - uses: chrislennon/action-aws-cli@v1.1
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        aws --endpoint-url=http://localhost:4566 s3 mb s3://testing
        npm version patch
        npm install
        npm install faker puppeteer@2.1.1 @userdashboard/dashboard --no-save
        git config --global user.name "${{ secrets.NAME }}"
        git config --global user.email "${{ secrets.EMAIL }}"
        npm install -g mocha standard
        mkdir -p node_modules/@userdashboard/storage-s3
        rm -rf node_modules/@userdashboard/storage-s3/src
        cp *.js node_modules/@userdashboard/storage-s3
        cp -R src/ node_modules/@userdashboard/storage-s3/src/
      env:
        AWS_SECRET_ACCESS_KEY: "using-mock-aws-s3"
        AWS_ACCESS_KEY_ID: "using-mock-aws-s3"
    - name: Lint (standard.js)
      run: standard src
    - name: Test
      run: mocha --file test-helper.js --bail --exit --full-trace --recursive --timeout 90000000 "./node_modules/@userdashboard/**/{,!(public)}/*.test.js" | tee tests.txt
      env:
        NODE_ENV: testing
        FAST_START: true
        DASHBOARD_SERVER: "http://localhost:9000"
        DOMAIN: "localhost"
        STORAGE: "@userdashboard/storage-s3"
        S3_ENDPOINT: "http://localhost:4566"
        S3_BUCKET_NAME: "testing"
        SECRET_ACCESS_KEY: "using-mock-aws-s3"
        ACCESS_KEY_ID: "using-mock-aws-s3"
        GENERATE_SITEMAP_TXT: false
        GENERATE_API_TXT: false
    - name: Publish to Github
      uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Automatically regenerated against current version
        branch: ${{ github.head_ref }}
        commit_options: '--no-verify --signoff'
        repository: .
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}